CREATE TABLE pokemon (
    p_Name  varchar(25) not null PRIMARY KEY,
    nationalNumber int not null,
    typeOne varchar(15) not null,
    typeTwo varchar(15),
    generation int not null,
    p_Description varchar(120) not null
);

CREATE TABLE breed (
    br_Name  varchar(25) not null,
    eggGroupOne varchar(15) not null,
    eggGroupTwo varchar(15),
    genderFemale_Percent float,
    genderMale_Percent float,
    eggCycle int not null,
    FOREIGN KEY(br_Name) REFERENCES pokemon(p_Name)
);

CREATE TABLE ability (
    a_Name varchar(25) not null PRIMARY KEY,
    a_Description varchar(120) not null
);

CREATE TABLE train (
    train_Name varchar(25) not null,
    evYield varchar(25) not null,
    catchRate int not null,
    baseFriendship int not null,
    baseExperience int not null,
    growthRate varchar(25) not null,
    FOREIGN KEY(train_Name) REFERENCES pokemon(p_Name)
);

CREATE TABLE typedefenses (
    type_Name varchar(25) not null,
    water float not null,
    electric float not null,
    fire float not null,
    grass float not null,
    ice float not null,
    fighting float not null,
    poison float not null,
    ground float not null,
    flying float not null,
    psychic float not null,
    bug float not null,
    rock float not null,
    ghost float not null,
    fairy float not null,
    dragon float not null,
    dark float not null,
    steel float not null,
    normal float not null,
    FOREIGN KEY(type_Name) REFERENCES pokemon(p_Name)
);

CREATE TABLE moves (
    m_Name varchar(40) not null PRIMARY KEY,
    type varchar(20) not null,
    power int,
    category varchar(25),
    PP int not null,
    accuracy int,
    effect varchar(120)
);

CREATE TABLE basestats (
    b_Name varchar(25) not null,
    attack int not null,
    defense int not null,
    hp int not null,
    speed int not null,
    spDefense int not null,
    spAttack int not null,
    total int not null,
    FOREIGN KEY(b_Name) REFERENCES pokemon(p_Name)
);

INSERT INTO pokemon(p_Name,nationalNumber,typeOne,typeTwo,generation,p_Description)
VALUES('bulbasaur',1,'grass','poison',1,'For some time after its birth, it grows by taking nourishment from the seed on its back.'),
('ivysaur',2,'grass','poison',1,''),
('venusaur',3,'grass','poison',1,''),
('charmander',4,'fire',null,1,''),
('charmeleon',5,'fire',null,1,''),
('charizard',6,'fire','flying',1,''),
('squirtle',7,'water',null,1,''),
('wartortle',8,'water',null,1,''),
('blastoise',9,'water',null,1,''),
('caterpie',10,'bug',null,1,''),
('metapod',11,'bug',null,1,''),
('butterfree',12,'bug','flying',1,''),
('weedle',13,'bug','poison',1,''),
('kakuna',14,'bug','poison',1,''),
('beedrill',15,'bug','poison',1,''),
('pidgey',16,'normal','flying',1,''),
('pidgeotto',17,'normal','flying',1,''),
('pidgeot',18,'normal','flying',1,''),
('rattata',19,'normal',null,1,''),
('raticate',20,'normal',null,1,''),
('spearow',21,'normal','flying',1,''),
('fearow',22,'normal','flying',1,''),
('ekans',23,'poison',null,1,''),
('arbok',24,'poison',null,1,''),
('pikachu',25,'electric',null,1,''),
('raichu',26,'electric',null,1,''),
('sandshrew',27,'ground',null,1,''),
('sandslash',28,'ground',null,1,''),
('nidoran♀',29,'poison',null,1,''),
('nidorina',30,'poison',null,1,''),
('nidoqueen',31,'poison','ground',1,''),
('nidoran♂',32,'poison',null,1,''),
('nidorino',33,'poison',null,1,''),
('nidoking',34,'poison','ground',1,''),
('clefairy',35,'fairy',null,1,''),
('clefable',36,'fairy',null,1,''),
('vulpix',37,'fire',null,1,''),
('ninetales',38,'fire',null,1,''),
('jigglypuff',39,'normal','fairy',1,''),
('wigglytuff',40,'normal','fairy',1,''),
('zubat',41,'poison','flying',1,''),
('golbat',42,'poison','flying',1,''),
('oddish',43,'grass','poison',1,''),
('gloom',44,'grass','poison',1,''),
('vileplume',45,'grass','poison',1,''),
('paras',46,'bug','grass',1,''),
('parasect',47,'bug','grass',1,''),
('venonat',48,'bug','poison',1,''),
('venomoth',49,'bug','poison',1,''),
('diglett',50,'ground',null,1,''),
('dugtrio',51,'ground',null,1,''),
('meowth',52,'normal',null,1,''),
('persian',53,'normal',null,1,''),
('psyduck',54,'water',null,1,''),
('golduck',55,'water',null,1,''),
('mankey',56,'fighting',null,1,''),
('primeape',57,'fighting',null,1,''),
('growlithe',58,'fire',null,1,''),
('arcanine',59,'fire',null,1,''),
('poliwag',60,'water',null,1,''),
('poliwhirl',61,'water',null,1,''),
('poliwrath',62,'water','fighting',1,''),
('abra',63,'psychic',null,1,''),
('kadabra',64,'psychic',null,1,''),
('alakazam',65,'psychic',null,1,''),
('machop',66,'fighting',null,1,''),
('machoke',67,'fighting',null,1,''),
('machamp',68,'fighting',null,1,''),
('bellsprout',69,'grass','poison',1,''),
('weepinbell',70,'grass','poison',1,''),
('victreebel',71,'grass','poison',1,''),
('tentacool',72,'water','poison',1,''),
('tentacruel',73,'water','poison',1,''),
('geodude',74,'rock','ground',1,''),
('graveler',75,'rock','ground',1,''),
('golem',76,'rock','ground',1,''),
('ponyta',77,'fire',null,1,''),
('rapidash',78,'fire',null,1,''),
('slowpoke',79,'water','psychic',1,''),
('slowbro',80,'water','psychic',1,''),
('magnemite',81,'electric','steel',1,''),
('magneton',82,'electric','steel',1,''),
('farfetch''d',83,'normal','flying',1,''),
('doduo',84,'normal','flying',1,''),
('dodrio',85,'normal','flying',1,''),
('seel',86,'water',null,1,''),
('dewgong',87,'water','ice',1,''),
('grimer',88,'poison',null,1,''),
('muk',89,'poison',null,1,''),
('shellder',90,'water',null,1,''),
('cloyster',91,'water','ice',1,''),
('gastly',92,'ghost','poison',1,''),
('haunter',93,'ghost','poison',1,''),
('gengar',94,'ghost','poison',1,''),
('onix',95,'rock','ground',1,''),
('drowzee',96,'psychic',null,1,''),
('hypno',97,'psychic',null,1,''),
('krabby',98,'water',null,1,''),
('kingler',99,'water',null,1,''),
('voltorb',100,'electric',null,1,''),
('electrode',101,'electric',null,1,''),
('exeggcute',102,'grass','psychic',1,''),
('exeggutor',103,'grass','psychic',1,''),
('cubone',104,'ground',null,1,''),
('marowak',105,'ground',null,1,''),
('hitmonlee',106,'fighting',null,1,''),
('hitmonchan',107,'fighting',null,1,''),
('lickitung',108,'normal',null,1,''),
('koffing',109,'poison',null,1,''),
('weezing',110,'poison',null,1,''),
('rhyhorn',111,'ground','rock',1,''),
('rhydon',112,'ground','rock',1,''),
('chansey',113,'normal',null,1,''),
('tangela',114,'grass',null,1,''),
('kangaskhan',115,'normal',null,1,''),
('horsea',116,'water',null,1,''),
('seadra',117,'water',null,1,''),
('goldeen',118,'water',null,1,''),
('seaking',119,'water',null,1,''),
('staryu',120,'water',null,1,''),
('starmie',121,'water','psychic',1,''),
('mr. mine',122,'psychic','fairy',1,''),
('scyther',123,'bug','flying',1,''),
('jynx',124,'ice','psychic',1,''),
('electabuzz',125,'electric',null,1,''),
('magmar',126,'fire',null,1,''),
('pinsir',127,'bug',null,1,''),
('tauros',128,'normal',null,1,''),
('magikarp',129,'water',null,1,''),
('gyarados',130,'water','flying',1,''),
('lapras',131,'water','ice',1,''),
('ditto',132,'normal',null,1,''),
('eevee',133,'normal',null,1,''),
('vaporeon',134,'water',null,1,''),
('jolteon',135,'electric',null,1,''),
('flareon',136,'fire',null,1,''),
('porygon',137,'normal',null,1,''),
('omanyte',138,'rock','water',1,''),
('omastar',139,'rock','water',1,''),
('kabuto',140,'rock','water',1,''),
('kabutops',141,'rock','water',1,''),
('aerodactyl',142,'rock','flying',1,''),
('snorlax',143,'normal',null,1,''),
('articuno',144,'ice','flying',1,''),
('zapdos',145,'electric','flying',1,''),
('moltres',146,'fire','flying',1,''),
('dratini',147,'dragon',null,1,''),
('dragonair',148,'dragon',null,1,''),
('dragonite',149,'dragon','flying',1,''),
('mewtwo',150,'psychic',null,1,''),
('mew',151,'psychic',null,1,'');